### ISSUE TITLE
not able to compile

### ISSUE THREAD

**Issue by kukomiguel** [MarginallyClever/Skycam#3]
I get the following errors when compiling:

AArduino:1.8.3 (Mac OS X), Tarjeta:"Arduino/Genuino Mega or Mega 2560, ATmega2560 (Mega 2560)"

motor:72: error: 'FORCE_INLINESegment' does not name a type
 FORCE_INLINE Segment *segment_get_working() {
 ^
motor:79: error: 'FORCE_INLINEint' does not name a type
 FORCE_INLINE int get_next_segment(int i) {
 ^
motor:84: error: 'FORCE_INLINEint' does not name a type
 FORCE_INLINE int get_prev_segment(int i) {
 ^
motor:221: error: variable or field 'recalculate_reverse2' declared void
 void recalculate_reverse2(Segment *prev,Segment *current,Segment *next) {
                           ^
motor:221: error: 'Segment' was not declared in this scope
motor:221: error: 'prev' was not declared in this scope
 void recalculate_reverse2(Segment *prev,Segment *current,Segment *next) {
                                    ^
motor:221: error: 'Segment' was not declared in this scope
 void recalculate_reverse2(Segment *prev,Segment *current,Segment *next) {
                                         ^
motor:221: error: 'current' was not declared in this scope
 void recalculate_reverse2(Segment *prev,Segment *current,Segment *next) {
                                                  ^
motor:221: error: 'Segment' was not declared in this scope
 void recalculate_reverse2(Segment *prev,Segment *current,Segment *next) {
                                                          ^
motor:221: error: 'next' was not declared in this scope
 void recalculate_reverse2(Segment *prev,Segment *current,Segment *next) {
                                                                   ^
motor:259: error: variable or field 'recalculate_forward2' declared void
 void recalculate_forward2(Segment *prev,Segment *current,Segment *next) {
                           ^
motor:259: error: 'Segment' was not declared in this scope
motor:259: error: 'prev' was not declared in this scope
 void recalculate_forward2(Segment *prev,Segment *current,Segment *next) {
                                    ^
motor:259: error: 'Segment' was not declared in this scope
 void recalculate_forward2(Segment *prev,Segment *current,Segment *next) {
                                         ^
motor:259: error: 'current' was not declared in this scope
 void recalculate_forward2(Segment *prev,Segment *current,Segment *next) {
                                                  ^
motor:259: error: 'Segment' was not declared in this scope
 void recalculate_forward2(Segment *prev,Segment *current,Segment *next) {
                                                          ^
motor:259: error: 'next' was not declared in this scope
 void recalculate_forward2(Segment *prev,Segment *current,Segment *next) {
                                                                   ^
motor:306: error: variable or field 'segment_update_trapezoid' declared void
 void segment_update_trapezoid(Segment *s,float start_speed,float end_speed) {
                               ^
motor:306: error: 'Segment' was not declared in this scope
motor:306: error: 's' was not declared in this scope
 void segment_update_trapezoid(Segment *s,float start_speed,float end_speed) {
                                        ^
motor:306: error: expected primary-expression before 'float'
 void segment_update_trapezoid(Segment *s,float start_speed,float end_speed) {
                                          ^
motor:306: error: expected primary-expression before 'float'
 void segment_update_trapezoid(Segment *s,float start_speed,float end_speed) {
                                                            ^
motor:443: error: 'FORCE_INLINEunsigned' does not name a type
 FORCE_INLINE unsigned short calc_timer(unsigned short desired_freq_hz) {
 ^
skycamFirmwareRumba:411: error: 'Vector3' does not name a type
 Vector3 get_end_plus_offset() {
 ^
/Users/Miguel/Dropbox/Architech/Skycam-master 4/skycamFirmwareRUMBA/eeprom.ino: In function 'char loadVersion()':
eeprom:39: error: 'ADDR_VERSION' was not declared in this scope
   return EEPROM.read(ADDR_VERSION);
                      ^
/Users/Miguel/Dropbox/Architech/Skycam-master 4/skycamFirmwareRUMBA/eeprom.ino: In function 'void loadConfig()':
eeprom:46: error: 'EEPROM_VERSION' was not declared in this scope
   if( versionNumber != EEPROM_VERSION ) {
                        ^
eeprom:49: error: 'ADDR_VERSION' was not declared in this scope
     EEPROM.write(ADDR_VERSION,EEPROM_VERSION);
                  ^
eeprom:53: error: 'robot_uid' was not declared in this scope
   robot_uid=EEPROM_readLong(ADDR_UUID);
   ^
eeprom:53: error: 'ADDR_UUID' was not declared in this scope
   robot_uid=EEPROM_readLong(ADDR_UUID);
                             ^
/Users/Miguel/Dropbox/Architech/Skycam-master 4/skycamFirmwareRUMBA/eeprom.ino: In function 'void saveUID()':
eeprom:61: error: 'ADDR_UUID' was not declared in this scope
   EEPROM_writeLong(ADDR_UUID,(long)robot_uid);
                    ^
eeprom:61: error: 'robot_uid' was not declared in this scope
   EEPROM_writeLong(ADDR_UUID,(long)robot_uid);
                                    ^
/Users/Miguel/Dropbox/Architech/Skycam-master 4/skycamFirmwareRUMBA/eeprom.ino: In function 'void saveDimensions()':
eeprom:68: error: 'ADDR_AX' was not declared in this scope
   EEPROM_writeLong(ADDR_AX,limit_ax*100);
                    ^
eeprom:68: error: 'limit_ax' was not declared in this scope
   EEPROM_writeLong(ADDR_AX,limit_ax*100);
                            ^
eeprom:69: error: 'ADDR_AY' was not declared in this scope
   EEPROM_writeLong(ADDR_AY,limit_ay*100);
                    ^
eeprom:69: error: 'limit_ay' was not declared in this scope
   EEPROM_writeLong(ADDR_AY,limit_ay*100);
                            ^
eeprom:70: error: 'ADDR_AZ' was not declared in this scope
   EEPROM_writeLong(ADDR_AZ,limit_az*100);
                    ^
eeprom:70: error: 'limit_az' was not declared in this scope
   EEPROM_writeLong(ADDR_AZ,limit_az*100);
                            ^
eeprom:72: error: 'ADDR_BX' was not declared in this scope
   EEPROM_writeLong(ADDR_BX,limit_bx*100);
                    ^
eeprom:72: error: 'limit_bx' was not declared in this scope
   EEPROM_writeLong(ADDR_BX,limit_bx*100);
                            ^
eeprom:73: error: 'ADDR_BY' was not declared in this scope
   EEPROM_writeLong(ADDR_BY,limit_by*100);
                    ^
eeprom:73: error: 'limit_by' was not declared in this scope
   EEPROM_writeLong(ADDR_BY,limit_by*100);
                            ^
eeprom:74: error: 'ADDR_BZ' was not declared in this scope
   EEPROM_writeLong(ADDR_BZ,limit_bz*100);
                    ^
eeprom:74: error: 'limit_bz' was not declared in this scope
   EEPROM_writeLong(ADDR_BZ,limit_bz*100);
                            ^
eeprom:76: error: 'ADDR_CX' was not declared in this scope
   EEPROM_writeLong(ADDR_CX,limit_cx*100);
                    ^
eeprom:76: error: 'limit_cx' was not declared in this scope
   EEPROM_writeLong(ADDR_CX,limit_cx*100);
                            ^
eeprom:77: error: 'ADDR_CY' was not declared in this scope
   EEPROM_writeLong(ADDR_CY,limit_cy*100);
                    ^
eeprom:77: error: 'limit_cy' was not declared in this scope
   EEPROM_writeLong(ADDR_CY,limit_cy*100);
                            ^
eeprom:78: error: 'ADDR_CZ' was not declared in this scope
   EEPROM_writeLong(ADDR_CZ,limit_cz*100);
                    ^
eeprom:78: error: 'limit_cz' was not declared in this scope
   EEPROM_writeLong(ADDR_CZ,limit_cz*100);
                            ^
eeprom:80: error: 'ADDR_DX' was not declared in this scope
   EEPROM_writeLong(ADDR_DX,limit_dx*100);
                    ^
eeprom:80: error: 'limit_dx' was not declared in this scope
   EEPROM_writeLong(ADDR_DX,limit_dx*100);
                            ^
eeprom:81: error: 'ADDR_DY' was not declared in this scope
   EEPROM_writeLong(ADDR_DY,limit_dy*100);
                    ^
eeprom:81: error: 'limit_dy' was not declared in this scope
   EEPROM_writeLong(ADDR_DY,limit_dy*100);
                            ^
eeprom:82: error: 'ADDR_DZ' was not declared in this scope
   EEPROM_writeLong(ADDR_DZ,limit_dz*100);
                    ^
eeprom:82: error: 'limit_dz' was not declared in this scope
   EEPROM_writeLong(ADDR_DZ,limit_dz*100);
                            ^
/Users/Miguel/Dropbox/Architech/Skycam-master 4/skycamFirmwareRUMBA/eeprom.ino: In function 'void loadDimensions()':
eeprom:88: error: 'limit_ax' was not declared in this scope
   limit_ax = (float)EEPROM_readLong(ADDR_AX)/100.0f;
   ^
eeprom:88: error: 'ADDR_AX' was not declared in this scope
   limit_ax = (float)EEPROM_readLong(ADDR_AX)/100.0f;
                                     ^
eeprom:89: error: 'limit_ay' was not declared in this scope
   limit_ay = (float)EEPROM_readLong(ADDR_AY)/100.0f;
   ^
eeprom:89: error: 'ADDR_AY' was not declared in this scope
   limit_ay = (float)EEPROM_readLong(ADDR_AY)/100.0f;
                                     ^
eeprom:90: error: 'limit_az' was not declared in this scope
   limit_az = (float)EEPROM_readLong(ADDR_AZ)/100.0f;
   ^
eeprom:90: error: 'ADDR_AZ' was not declared in this scope
   limit_az = (float)EEPROM_readLong(ADDR_AZ)/100.0f;
                                     ^
eeprom:92: error: 'limit_bx' was not declared in this scope
   limit_bx = (float)EEPROM_readLong(ADDR_BX)/100.0f;
   ^
eeprom:92: error: 'ADDR_BX' was not declared in this scope
   limit_bx = (float)EEPROM_readLong(ADDR_BX)/100.0f;
                                     ^
eeprom:93: error: 'limit_by' was not declared in this scope
   limit_by = (float)EEPROM_readLong(ADDR_BY)/100.0f;
   ^
eeprom:93: error: 'ADDR_BY' was not declared in this scope
   limit_by = (float)EEPROM_readLong(ADDR_BY)/100.0f;
                                     ^
eeprom:94: error: 'limit_bz' was not declared in this scope
   limit_bz = (float)EEPROM_readLong(ADDR_BZ)/100.0f;
   ^
eeprom:94: error: 'ADDR_BZ' was not declared in this scope
   limit_bz = (float)EEPROM_readLong(ADDR_BZ)/100.0f;
                                     ^
eeprom:96: error: 'limit_cx' was not declared in this scope
   limit_cx = (float)EEPROM_readLong(ADDR_CX)/100.0f;
   ^
eeprom:96: error: 'ADDR_CX' was not declared in this scope
   limit_cx = (float)EEPROM_readLong(ADDR_CX)/100.0f;
                                     ^
eeprom:97: error: 'limit_cy' was not declared in this scope
   limit_cy = (float)EEPROM_readLong(ADDR_CY)/100.0f;
   ^
eeprom:97: error: 'ADDR_CY' was not declared in this scope
   limit_cy = (float)EEPROM_readLong(ADDR_CY)/100.0f;
                                     ^
eeprom:98: error: 'limit_cz' was not declared in this scope
   limit_cz = (float)EEPROM_readLong(ADDR_CZ)/100.0f;
   ^
eeprom:98: error: 'ADDR_CZ' was not declared in this scope
   limit_cz = (float)EEPROM_readLong(ADDR_CZ)/100.0f;
                                     ^
eeprom:100: error: 'limit_dx' was not declared in this scope
   limit_dx = (float)EEPROM_readLong(ADDR_DX)/100.0f;
   ^
eeprom:100: error: 'ADDR_DX' was not declared in this scope
   limit_dx = (float)EEPROM_readLong(ADDR_DX)/100.0f;
                                     ^
eeprom:101: error: 'limit_dy' was not declared in this scope
   limit_dy = (float)EEPROM_readLong(ADDR_DY)/100.0f;
   ^
eeprom:101: error: 'ADDR_DY' was not declared in this scope
   limit_dy = (float)EEPROM_readLong(ADDR_DY)/100.0f;
                                     ^
eeprom:102: error: 'limit_dz' was not declared in this scope
   limit_dz = (float)EEPROM_readLong(ADDR_DZ)/100.0f;
   ^
eeprom:102: error: 'ADDR_DZ' was not declared in this scope
   limit_dz = (float)EEPROM_readLong(ADDR_DZ)/100.0f;
                                     ^
/Users/Miguel/Dropbox/Architech/Skycam-master 4/skycamFirmwareRUMBA/eeprom.ino: In function 'void adjustDimensions(float, float, float, float, float, float, float, float, float, float, float, float)':
eeprom:117: error: 'limit_ax' was not declared in this scope
   v = floor(ax*100)/100.0f;  if(limit_ax != ax) { limit_ax = ax; changed=1; }  
                                 ^
eeprom:118: error: 'limit_ay' was not declared in this scope
   v = floor(ay*100)/100.0f;  if(limit_ay != ay) { limit_ay = ay; changed=1; }  
                                 ^
eeprom:119: error: 'limit_az' was not declared in this scope
   v = floor(az*100)/100.0f;  if(limit_az != az) { limit_az = az; changed=1; }
                                 ^
eeprom:120: error: 'limit_bx' was not declared in this scope
   v = floor(bx*100)/100.0f;  if(limit_bx != bx) { limit_ax = bx; changed=1; }  
                                 ^
eeprom:120: error: 'limit_ax' was not declared in this scope
   v = floor(bx*100)/100.0f;  if(limit_bx != bx) { limit_ax = bx; changed=1; }  
                                                   ^
eeprom:121: error: 'limit_by' was not declared in this scope
   v = floor(by*100)/100.0f;  if(limit_by != by) { limit_ay = by; changed=1; }  
                                 ^
eeprom:121: error: 'limit_ay' was not declared in this scope
   v = floor(by*100)/100.0f;  if(limit_by != by) { limit_ay = by; changed=1; }  
                                                   ^
eeprom:122: error: 'limit_bz' was not declared in this scope
   v = floor(bz*100)/100.0f;  if(limit_bz != bz) { limit_az = bz; changed=1; }  
                                 ^
eeprom:122: error: 'limit_az' was not declared in this scope
   v = floor(bz*100)/100.0f;  if(limit_bz != bz) { limit_az = bz; changed=1; }  
                                                   ^
eeprom:123: error: 'limit_cx' was not declared in this scope
   v = floor(cx*100)/100.0f;  if(limit_cx != cx) { limit_ax = cx; changed=1; }  
                                 ^
eeprom:123: error: 'limit_ax' was not declared in this scope
   v = floor(cx*100)/100.0f;  if(limit_cx != cx) { limit_ax = cx; changed=1; }  
                                                   ^
eeprom:124: error: 'limit_cy' was not declared in this scope
   v = floor(cy*100)/100.0f;  if(limit_cy != cy) { limit_ay = cy; changed=1; }  
                                 ^
eeprom:124: error: 'limit_ay' was not declared in this scope
   v = floor(cy*100)/100.0f;  if(limit_cy != cy) { limit_ay = cy; changed=1; }  
                                                   ^
eeprom:125: error: 'limit_cz' was not declared in this scope
   v = floor(cz*100)/100.0f;  if(limit_cz != cz) { limit_az = cz; changed=1; }  
                                 ^
eeprom:125: error: 'limit_az' was not declared in this scope
   v = floor(cz*100)/100.0f;  if(limit_cz != cz) { limit_az = cz; changed=1; }  
                                                   ^
eeprom:126: error: 'limit_dx' was not declared in this scope
   v = floor(dx*100)/100.0f;  if(limit_dx != dx) { limit_ax = dx; changed=1; }  
                                 ^
eeprom:126: error: 'limit_ax' was not declared in this scope
   v = floor(dx*100)/100.0f;  if(limit_dx != dx) { limit_ax = dx; changed=1; }  
                                                   ^
eeprom:127: error: 'limit_dy' was not declared in this scope
   v = floor(dy*100)/100.0f;  if(limit_dy != dy) { limit_ay = dy; changed=1; }  
                                 ^
eeprom:127: error: 'limit_ay' was not declared in this scope
   v = floor(dy*100)/100.0f;  if(limit_dy != dy) { limit_ay = dy; changed=1; }  
                                                   ^
eeprom:128: error: 'limit_dz' was not declared in this scope
   v = floor(dz*100)/100.0f;  if(limit_dz != dz) { limit_az = dz; changed=1; }  
                                 ^
eeprom:128: error: 'limit_az' was not declared in this scope
   v = floor(dz*100)/100.0f;  if(limit_dz != dz) { limit_az = dz; changed=1; }  
                                                   ^
/Users/Miguel/Dropbox/Architech/Skycam-master 4/skycamFirmwareRUMBA/motor.ino: At global scope:
motor:18: error: 'Axis' does not name a type
 Axis a[NUM_MOTORS];  // for line()
 ^
motor:19: error: 'Axis' does not name a type
 Axis atemp;  // for line()
 ^
motor:20: error: 'Motor' does not name a type
 Motor motors[NUM_MOTORS];
 ^
motor:22: error: 'Segment' does not name a type
 Segment line_segments[MAX_SEGMENTS];
 ^
motor:23: error: 'Segment' does not name a type
 Segment *working_seg = NULL;
 ^
motor:29: error: 'NUM_SERVOS' was not declared in this scope
 Servo servos[NUM_SERVOS];
              ^
motor:39: error: 'MAX_JERK' was not declared in this scope
 float max_xy_jerk = MAX_JERK;
                     ^
motor:72: error: 'FORCE_INLINE' does not name a type
 FORCE_INLINE Segment *segment_get_working() {
 ^
motor:79: error: 'FORCE_INLINE' does not name a type
 FORCE_INLINE int get_next_segment(int i) {
 ^
motor:84: error: 'FORCE_INLINE' does not name a type
 FORCE_INLINE int get_prev_segment(int i) {
 ^
/Users/Miguel/Dropbox/Architech/Skycam-master 4/skycamFirmwareRUMBA/motor.ino: In function 'void motor_setup()':
motor:99: error: 'motors' was not declared in this scope
   motors[0].step_pin        =MOTOR_0_STEP_PIN;
   ^
motor:99: error: 'MOTOR_0_STEP_PIN' was not declared in this scope
   motors[0].step_pin        =MOTOR_0_STEP_PIN;
                              ^
motor:100: error: 'MOTOR_0_DIR_PIN' was not declared in this scope
   motors[0].dir_pin         =MOTOR_0_DIR_PIN;
                              ^
motor:101: error: 'MOTOR_0_ENABLE_PIN' was not declared in this scope
   motors[0].enable_pin      =MOTOR_0_ENABLE_PIN;
                              ^
motor:102: error: 'MOTOR_0_LIMIT_SWITCH_PIN' was not declared in this scope
   motors[0].limit_switch_pin=MOTOR_0_LIMIT_SWITCH_PIN;
                              ^
motor:104: error: 'MOTOR_1_STEP_PIN' was not declared in this scope
   motors[1].step_pin        =MOTOR_1_STEP_PIN;
                              ^
motor:105: error: 'MOTOR_1_DIR_PIN' was not declared in this scope
   motors[1].dir_pin         =MOTOR_1_DIR_PIN;
                              ^
motor:106: error: 'MOTOR_1_ENABLE_PIN' was not declared in this scope
   motors[1].enable_pin      =MOTOR_1_ENABLE_PIN;
                              ^
motor:107: error: 'MOTOR_1_LIMIT_SWITCH_PIN' was not declared in this scope
   motors[1].limit_switch_pin=MOTOR_1_LIMIT_SWITCH_PIN;
                              ^
motor:122: error: 'NUM_MOTORS' was not declared in this scope
   for(i=0;i<NUM_MOTORS;++i) {
             ^
motor:134: error: 'NUM_MOTORS' was not declared in this scope
   long steps[NUM_MOTORS];
              ^
motor:135: error: 'steps' was not declared in this scope
   memset(steps,0,NUM_MOTORS*sizeof(long));
          ^
motor:157: error: 'Segment' was not declared in this scope
   Segment &old_seg = line_segments[get_prev_segment(last_segment)];
   ^
motor:157: error: 'old_seg' was not declared in this scope
   Segment &old_seg = line_segments[get_prev_segment(last_segment)];
            ^
motor:157: error: 'line_segments' was not declared in this scope
   Segment &old_seg = line_segments[get_prev_segment(last_segment)];
                      ^
motor:157: error: 'get_prev_segment' was not declared in this scope
   Segment &old_seg = line_segments[get_prev_segment(last_segment)];
                                                                 ^
motor:167: error: 'working_seg' was not declared in this scope
   working_seg = NULL;
   ^
/Users/Miguel/Dropbox/Architech/Skycam-master 4/skycamFirmwareRUMBA/motor.ino: In function 'void motor_engage()':
motor:191: error: 'NUM_MOTORS' was not declared in this scope
   for(i=0;i<NUM_MOTORS;++i) {
             ^
motor:192: error: 'motors' was not declared in this scope
     digitalWrite(motors[i].enable_pin,LOW);
                  ^
/Users/Miguel/Dropbox/Architech/Skycam-master 4/skycamFirmwareRUMBA/motor.ino: In function 'void motor_disengage()':
motor:200: error: 'NUM_MOTORS' was not declared in this scope
   for(i=0;i<NUM_MOTORS;++i) {
             ^
motor:201: error: 'motors' was not declared in this scope
     digitalWrite(motors[i].enable_pin,HIGH);
                  ^
/Users/Miguel/Dropbox/Architech/Skycam-master 4/skycamFirmwareRUMBA/motor.ino: In function 'void setPenAngle(int)':
motor:208: error: 'posz' was not declared in this scope
   if(posz!=pen_angle) {
      ^
motor:211: error: 'PEN_DOWN_ANGLE' was not declared in this scope
     if(posz<PEN_DOWN_ANGLE) posz=PEN_DOWN_ANGLE;
             ^
motor:212: error: 'PEN_UP_ANGLE' was not declared in this scope
     if(posz>PEN_UP_ANGLE  ) posz=PEN_UP_ANGLE;
             ^
motor:214: error: 'struct servo_t' has no member named 'write'
     servos[0].write(posz);
               ^
/Users/Miguel/Dropbox/Architech/Skycam-master 4/skycamFirmwareRUMBA/motor.ino: At global scope:
motor:221: error: variable or field 'recalculate_reverse2' declared void
 void recalculate_reverse2(Segment *prev,Segment *current,Segment *next) {
                           ^
motor:221: error: 'Segment' was not declared in this scope
motor:221: error: 'prev' was not declared in this scope
 void recalculate_reverse2(Segment *prev,Segment *current,Segment *next) {
                                    ^
motor:221: error: 'Segment' was not declared in this scope
 void recalculate_reverse2(Segment *prev,Segment *current,Segment *next) {
                                         ^
motor:221: error: 'current' was not declared in this scope
 void recalculate_reverse2(Segment *prev,Segment *current,Segment *next) {
                                                  ^
motor:221: error: 'Segment' was not declared in this scope
 void recalculate_reverse2(Segment *prev,Segment *current,Segment *next) {
                                                          ^
motor:221: error: 'next' was not declared in this scope
 void recalculate_reverse2(Segment *prev,Segment *current,Segment *next) {
                                                                   ^
exit status 1
'FORCE_INLINESegment' does not name a type

**Comment by i-make-robots** [comment]
These are known.  I've been working through it all last night and this morning.  I'll push an update when it's ready for testing.

**Comment by i-make-robots** [comment]
should be compiling ok now.

**Comment by kukomiguel** [comment]
I changed this section of the code to include RAMPS

// Your choice of board
//#define MOTHERBOARD BOARD_RUMBA
#define MOTHERBOARD BOARD_RAMPS

#if MOTHERBOARD == BOARD_RUMBA 

#define HAS_SD                   // comment this out if there is no SD card
#define HAS_LCD                  // comment this out if there is no SMART LCD controller


#define MAX_MOTORS                 (6)

#define MOTOR_0_DIR_PIN           (16)
#define MOTOR_0_STEP_PIN          (17)
#define MOTOR_0_ENABLE_PIN        (48)
#define MOTOR_0_LIMIT_SWITCH_PIN  (37)

#define MOTOR_1_DIR_PIN           (47)
#define MOTOR_1_STEP_PIN          (54)
#define MOTOR_1_ENABLE_PIN        (55)
#define MOTOR_1_LIMIT_SWITCH_PIN  (36)

// alternate pins in case you want to do something interesting
#define MOTOR_2_DIR_PIN           (56)
#define MOTOR_2_STEP_PIN          (57)
#define MOTOR_2_ENABLE_PIN        (62)
#define MOTOR_2_LIMIT_SWITCH_PIN  (35)

#define MOTOR_3_DIR_PIN           (22)
#define MOTOR_3_STEP_PIN          (23)
#define MOTOR_3_ENABLE_PIN        (24)
#define MOTOR_3_LIMIT_SWITCH_PIN  (34)

#define MOTOR_4_DIR_PIN           (25)
#define MOTOR_4_STEP_PIN          (26)
#define MOTOR_4_ENABLE_PIN        (27)
#define MOTOR_4_LIMIT_SWITCH_PIN  (33)

#define MOTOR_5_DIR_PIN           (28)
#define MOTOR_5_STEP_PIN          (29)
#define MOTOR_5_ENABLE_PIN        (39)
#define MOTOR_5_LIMIT_SWITCH_PIN  (32)

#define LIMIT_SWITCH_PIN_LEFT     (MOTOR_0_LIMIT_SWITCH_PIN)
#define LIMIT_SWITCH_PIN_RIGHT    (MOTOR_1_LIMIT_SWITCH_PIN)

// Smart controller settings
#define BEEPER             44
#define LCD_PINS_RS        19
#define LCD_PINS_ENABLE    42
#define LCD_PINS_D4        18
#define LCD_PINS_D5        38
#define LCD_PINS_D6        41
#define LCD_PINS_D7        40

// Encoder rotation values
#define BTN_EN1            11
#define BTN_EN2            12
#define BTN_ENC            43
#endif

#if MOTHERBOARD == BOARD_RAMPS 

#define MAX_MOTORS                 (5)
#define MOTOR_0_DIR_PIN           (55)
#define MOTOR_0_STEP_PIN          (54)
#define MOTOR_0_ENABLE_PIN        (38)
#define MOTOR_0_LIMIT_SWITCH_PIN  (3)   /* X min */

#define MOTOR_1_DIR_PIN           (61)
#define MOTOR_1_STEP_PIN          (60)
#define MOTOR_1_ENABLE_PIN        (56)
#define MOTOR_1_LIMIT_SWITCH_PIN  (14)  /* Y min */

// alternate pins in case you want to do something interesting
#define MOTOR_2_DIR_PIN           (48)
#define MOTOR_2_STEP_PIN          (46)
#define MOTOR_2_ENABLE_PIN        (62)
#define MOTOR_2_LIMIT_SWITCH_PIN  (18)  /* Z Min */

#define MOTOR_3_DIR_PIN           (28)
#define MOTOR_3_STEP_PIN          (26)
#define MOTOR_3_ENABLE_PIN        (24)
#define MOTOR_3_LIMIT_SWITCH_PIN  (2)   /* X Max */

#define MOTOR_4_DIR_PIN           (34)
#define MOTOR_4_STEP_PIN          (36)
#define MOTOR_4_ENABLE_PIN        (30)
#define MOTOR_4_LIMIT_SWITCH_PIN  (15)  /* Y Max */

#define NUM_SERVOS         (4)
#define SERVO0_PIN         (11)   /* Servo 1 */
#define SERVO1_PIN         (6)
#define SERVO2_PIN         (5)
#define SERVO3_PIN         (4)

// Smart controller settings
#define BEEPER             37   /* Pin on SMART Adapter */
#define LCD_PINS_RS        16   /* Pin on SMART Adapter */
#define LCD_PINS_ENABLE    17   /* Pin on SMART Adapter */ 
#define LCD_PINS_D4        23   /* Pin on SMART Adapter */
#define LCD_PINS_D5        25   /* Pin on SMART Adapter */
#define LCD_PINS_D6        27   /* Pin on SMART Adapter */
#define LCD_PINS_D7        29   /* Pin on SMART Adapter */

// Encoder rotation values
#define BTN_EN1            31   /* Pin on SMART Adapter */
#define BTN_EN2            33   /* Pin on SMART Adapter */
#define BTN_ENC            35  /* Pin on SMART Adapter */

#define KILL_PIN    41    /* Pin on SMART Adapter */
#endif


#if NUM_MOTORS > MAX_MOTORS
#error "The number of motors needed is more than this board supports."
#endif
